"""
ml/scoring.py
─────────────────────────────────────────────────────────────────────────────
AAROGYA — Deterministic Baseline Scoring Engine (Score Version: v1.0)
─────────────────────────────────────────────────────────────────────────────

DESIGN PRINCIPLE
────────────────
Rules Calculate → ML Learns → SHAP Explains → AI Communicates → Preferences Personalize

This module computes the Aarogya Food Insight Score (0–100) using a fully
transparent, deterministic rule-based methodology. It does NOT use Gemini,
any LLM, or any black-box model to generate the numerical score.

The score created here becomes the TARGET VARIABLE (y) for ML training.

IMPORTANT LIMITATIONS (Academically Required Disclosure)
──────────────────────────────────────────────────────────
1. Label Bias:         Score labels are generated by these rules. If the ML
                       model is trained on them, it may simply learn to imitate
                       the rules rather than discovering independent patterns.
2. Rule Imitation:     The trained model's "intelligence" is bounded by the
                       quality of these rules — not real-world nutritional truth.
3. No Clinical Validation: These thresholds are inspired by WHO/ICMR-NIN
                            guidelines but are NOT medically validated.
4. Circularity Risk:   Deterministic label → ML prediction → SHAP explanation
                       may explain the rules, not latent nutritional insight.
HOW TO IMPROVE LATER:
   - Expert annotation (nutritionists label sample products)
   - Validated scoring frameworks (NutriScore, FSSAI)
   - Pairwise human preference labels
   - Benchmark datasets with independent ground truth

SCORE_VERSION = "v1.0" — Update this when scoring logic changes.
"""

import numpy as np
import pandas as pd

# ─── Score Version ────────────────────────────────────────────────────────────
SCORE_VERSION = "v1.0"

# ─── Nutrient Thresholds (per 100g) ──────────────────────────────────────────
# Inspired by WHO daily intake recommendations, ICMR-NIN Indian RDA,
# and common nutritional labeling standards.
#
# These are reference-level thresholds, not clinical guidelines.
# Treat them as design decisions, not scientific facts.

THRESHOLDS = {
    # --- Sugar (g per 100g) ---
    # WHO recommends <10% of daily calories from free sugars (~50g/day).
    # Per 100g: low < 5g, moderate 5–15g, high > 15g
    "sugar": {
        "excellent": 0.0,    # 0–2g  → full points
        "good":      2.0,    # 2–5g
        "moderate":  5.0,    # 5–10g
        "high":      10.0,   # 10–20g
        "very_high": 20.0,   # >20g  → minimum points
        "direction": "lower_is_better"
    },

    # --- Protein (g per 100g) ---
    # ICMR-NIN adult RDA ~0.83g/kg bodyweight.
    # Per 100g: <5g low, 5–10g moderate, >10g good, >20g excellent
    "protein": {
        "low":      5.0,
        "moderate": 10.0,
        "good":     20.0,
        "excellent": 30.0,
        "direction": "higher_is_better"
    },

    # --- Fiber (g per 100g) ---
    # ICMR-NIN recommendation: 40g/day total dietary fiber.
    # Per 100g: <2g low, 2–4g moderate, 4–7g good, >7g excellent
    "fiber": {
        "low":      2.0,
        "moderate": 4.0,
        "good":     7.0,
        "excellent": 10.0,
        "direction": "higher_is_better"
    },

    # --- Sodium (mg per 100g) ---
    # WHO: <2000mg/day. Per 100g: <200mg good, 200–400mg moderate, >600mg high
    "sodium": {
        "excellent": 200.0,
        "good":      400.0,
        "moderate":  600.0,
        "high":      900.0,
        "direction": "lower_is_better"
    },

    # --- Saturated Fat (g per 100g) ---
    # WHO: <10% of energy from saturated fat (~22g/day at 2000kcal).
    # Per 100g: <3g low, 3–7g moderate, >10g high
    "saturated_fat": {
        "excellent": 3.0,
        "good":      7.0,
        "moderate":  10.0,
        "high":      15.0,
        "direction": "lower_is_better"
    },

    # --- Calories (kcal per 100g) ---
    # Reference: ~400 kcal/100g is typical for dry snack foods.
    # Very high caloric density without nutritional value warrants penalty.
    "energy": {
        "low":       250.0,
        "moderate":  400.0,
        "high":      500.0,
        "very_high": 600.0,
        "direction": "lower_is_better"
    },
}

# ─── Component Weights ────────────────────────────────────────────────────────
# Weights must sum to 1.0.
# WHY THESE WEIGHTS? 
#   Sugar and sodium are primary public health concerns in Indian packaged foods.
#   Protein and fiber are under-consumed nutrients.
#   Saturated fat and calories complete the picture.
#   IMPORTANT: These weights are DESIGN DECISIONS, not scientific consensus.
#   They should be validated by domain experts in a real-world deployment.

COMPONENT_WEIGHTS = {
    "sugar":         0.25,   # Highest weight — leading concern in Indian snacks
    "protein":       0.20,   # Under-consumed in typical Indian packaged food
    "fiber":         0.20,   # Under-consumed; protective for metabolic health
    "sodium":        0.15,   # High prevalence of excess sodium in Indian snacks
    "saturated_fat": 0.12,   # Relevant for cardiovascular health context
    "energy":        0.08,   # Energy density; lower weight as context-dependent
}

assert abs(sum(COMPONENT_WEIGHTS.values()) - 1.0) < 1e-9, \
    "Component weights must sum to 1.0"

# ─── Processing Level Modifier ────────────────────────────────────────────────
# NOVA classification-inspired adjustments.
# Minimally processed products receive a small bonus.
# Ultra-processed products receive a small penalty.
# These are adjustments, not the primary score.

PROCESSING_MODIFIER = {
    "minimally_processed":  +5.0,
    "processed":             0.0,
    "ultra_processed":      -8.0,
    "unclassified":          0.0,
}

# ─── Ingredient Modifiers ─────────────────────────────────────────────────────
CONTAINS_WHOLE_GRAIN_BONUS      = +3.0
CONTAINS_ARTIFICIAL_SWEETENER_PENALTY = -3.0
# Note: these are small modifiers, not the primary driver of score


# ─────────────────────────────────────────────────────────────────────────────
# COMPONENT SCORING FUNCTIONS
# Each function returns a score between 0 and 100 for ONE nutrient.
# ─────────────────────────────────────────────────────────────────────────────

def _score_sugar(sugar_g: float) -> float:
    """
    Lower sugar → higher score.
    Uses linear interpolation between defined thresholds.
    Returns 0–100.
    """
    if pd.isna(sugar_g):
        return 50.0   # UNKNOWN ≠ ZERO: assign neutral score, not 0 or 100
    if sugar_g <= 2.0:
        return 100.0
    elif sugar_g <= 5.0:
        return _lerp(sugar_g, 2.0, 5.0, 100.0, 80.0)
    elif sugar_g <= 10.0:
        return _lerp(sugar_g, 5.0, 10.0, 80.0, 55.0)
    elif sugar_g <= 20.0:
        return _lerp(sugar_g, 10.0, 20.0, 55.0, 25.0)
    else:
        return max(0.0, 25.0 - (sugar_g - 20.0) * 0.5)


def _score_protein(protein_g: float) -> float:
    """
    Higher protein → higher score.
    Returns 0–100.
    """
    if pd.isna(protein_g):
        return 50.0
    if protein_g >= 30.0:
        return 100.0
    elif protein_g >= 20.0:
        return _lerp(protein_g, 20.0, 30.0, 80.0, 100.0)
    elif protein_g >= 10.0:
        return _lerp(protein_g, 10.0, 20.0, 55.0, 80.0)
    elif protein_g >= 5.0:
        return _lerp(protein_g, 5.0, 10.0, 30.0, 55.0)
    else:
        return max(0.0, protein_g * 6.0)


def _score_fiber(fiber_g: float) -> float:
    """
    Higher fiber → higher score.
    Returns 0–100.
    """
    if pd.isna(fiber_g):
        return 50.0
    if fiber_g >= 10.0:
        return 100.0
    elif fiber_g >= 7.0:
        return _lerp(fiber_g, 7.0, 10.0, 80.0, 100.0)
    elif fiber_g >= 4.0:
        return _lerp(fiber_g, 4.0, 7.0, 55.0, 80.0)
    elif fiber_g >= 2.0:
        return _lerp(fiber_g, 2.0, 4.0, 30.0, 55.0)
    else:
        return max(0.0, fiber_g * 15.0)


def _score_sodium(sodium_mg: float) -> float:
    """
    Lower sodium → higher score.
    Returns 0–100.
    """
    if pd.isna(sodium_mg):
        return 50.0
    if sodium_mg <= 200.0:
        return 100.0
    elif sodium_mg <= 400.0:
        return _lerp(sodium_mg, 200.0, 400.0, 100.0, 75.0)
    elif sodium_mg <= 600.0:
        return _lerp(sodium_mg, 400.0, 600.0, 75.0, 50.0)
    elif sodium_mg <= 900.0:
        return _lerp(sodium_mg, 600.0, 900.0, 50.0, 25.0)
    else:
        return max(0.0, 25.0 - (sodium_mg - 900.0) * 0.02)


def _score_saturated_fat(sat_fat_g: float) -> float:
    """
    Lower saturated fat → higher score.
    Returns 0–100.
    """
    if pd.isna(sat_fat_g):
        return 50.0
    if sat_fat_g <= 3.0:
        return 100.0
    elif sat_fat_g <= 7.0:
        return _lerp(sat_fat_g, 3.0, 7.0, 100.0, 70.0)
    elif sat_fat_g <= 10.0:
        return _lerp(sat_fat_g, 7.0, 10.0, 70.0, 45.0)
    elif sat_fat_g <= 15.0:
        return _lerp(sat_fat_g, 10.0, 15.0, 45.0, 20.0)
    else:
        return max(0.0, 20.0 - (sat_fat_g - 15.0) * 1.0)


def _score_energy(energy_kcal: float) -> float:
    """
    Lower caloric density → higher score (penalizes energy-dense, nutrient-poor items).
    Context-dependent: protein bars at 400kcal are very different from candy at 400kcal.
    This is WHY energy weight is kept lower (0.08) than nutrients like protein/fiber.
    Returns 0–100.
    """
    if pd.isna(energy_kcal):
        return 50.0
    if energy_kcal <= 250.0:
        return 100.0
    elif energy_kcal <= 400.0:
        return _lerp(energy_kcal, 250.0, 400.0, 100.0, 70.0)
    elif energy_kcal <= 500.0:
        return _lerp(energy_kcal, 400.0, 500.0, 70.0, 45.0)
    elif energy_kcal <= 600.0:
        return _lerp(energy_kcal, 500.0, 600.0, 45.0, 20.0)
    else:
        return max(0.0, 20.0 - (energy_kcal - 600.0) * 0.05)


# ─── Helper: Linear Interpolation ─────────────────────────────────────────────

def _lerp(value: float, x0: float, x1: float, y0: float, y1: float) -> float:
    """Linear interpolation between two threshold points."""
    t = (value - x0) / (x1 - x0)
    return y0 + t * (y1 - y0)


# ─────────────────────────────────────────────────────────────────────────────
# MAIN SCORING FUNCTION
# ─────────────────────────────────────────────────────────────────────────────

def compute_aarogya_score(row: pd.Series) -> dict:
    """
    Compute the Aarogya Food Insight Score for a single product row.

    Parameters
    ----------
    row : pd.Series
        A single row from the product DataFrame. Expected columns:
        sugar_g_100g, protein_g_100g, fiber_g_100g, sodium_mg_100g,
        saturated_fat_g_100g, energy_kcal_100g, processing_level,
        contains_whole_grain, contains_artificial_sweetener

    Returns
    -------
    dict with keys:
        final_score (float, 0–100, clipped)
        component_scores (dict of per-nutrient 0–100 scores)
        modifiers (dict of modifier values applied)
        score_version (str)
        breakdown (dict for SHAP/explanation use)
    """
    # ── Step 1: Per-nutrient component scores ─────────────────────────────────
    component_scores = {
        "sugar":         _score_sugar(row.get("sugar_g_100g")),
        "protein":       _score_protein(row.get("protein_g_100g")),
        "fiber":         _score_fiber(row.get("fiber_g_100g")),
        "sodium":        _score_sodium(row.get("sodium_mg_100g")),
        "saturated_fat": _score_saturated_fat(row.get("saturated_fat_g_100g")),
        "energy":        _score_energy(row.get("energy_kcal_100g")),
    }

    # ── Step 2: Weighted combination ──────────────────────────────────────────
    weighted_score = sum(
        component_scores[nutrient] * weight
        for nutrient, weight in COMPONENT_WEIGHTS.items()
    )

    # ── Step 3: Processing level modifier ─────────────────────────────────────
    proc_level = str(row.get("processing_level", "unclassified")).lower()
    processing_mod = PROCESSING_MODIFIER.get(proc_level, 0.0)

    # ── Step 4: Ingredient modifiers ──────────────────────────────────────────
    whole_grain_mod = 0.0
    if str(row.get("contains_whole_grain", "false")).lower() in ("true", "1", "yes"):
        whole_grain_mod = CONTAINS_WHOLE_GRAIN_BONUS

    sweetener_mod = 0.0
    if str(row.get("contains_artificial_sweetener", "false")).lower() in ("true", "1", "yes"):
        sweetener_mod = CONTAINS_ARTIFICIAL_SWEETENER_PENALTY

    total_modifier = processing_mod + whole_grain_mod + sweetener_mod

    # ── Step 5: Final score ────────────────────────────────────────────────────
    final_score = weighted_score + total_modifier
    final_score = float(np.clip(final_score, 0.0, 100.0))

    # ── Step 6: Breakdown dict (used by SHAP + Gemini explanation layer) ──────
    breakdown = {
        "weighted_component_score": round(weighted_score, 2),
        "processing_modifier":      round(processing_mod, 2),
        "whole_grain_modifier":     round(whole_grain_mod, 2),
        "sweetener_modifier":       round(sweetener_mod, 2),
        "total_modifier":           round(total_modifier, 2),
        "strengths": [
            k for k, v in component_scores.items()
            if v >= 75 and COMPONENT_WEIGHTS.get(k, 0) >= 0.10
        ],
        "concerns": [
            k for k, v in component_scores.items()
            if v <= 40 and COMPONENT_WEIGHTS.get(k, 0) >= 0.10
        ],
    }

    return {
        "final_score":      round(final_score, 2),
        "component_scores": {k: round(v, 2) for k, v in component_scores.items()},
        "modifiers": {
            "processing":   round(processing_mod, 2),
            "whole_grain":  round(whole_grain_mod, 2),
            "sweetener":    round(sweetener_mod, 2),
        },
        "score_version": SCORE_VERSION,
        "breakdown":     breakdown,
    }


def score_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """
    Apply compute_aarogya_score to every row of a DataFrame.

    Returns the original DataFrame with new columns added:
        computed_score, score_version, strengths, concerns
    """
    results = df.apply(compute_aarogya_score, axis=1)

    df = df.copy()
    df["computed_score"]   = results.apply(lambda r: r["final_score"])
    df["score_version"]    = SCORE_VERSION
    df["score_strengths"]  = results.apply(lambda r: "|".join(r["breakdown"]["strengths"]))
    df["score_concerns"]   = results.apply(lambda r: "|".join(r["breakdown"]["concerns"]))

    return df


# ─────────────────────────────────────────────────────────────────────────────
# Quick Test — Run directly: python ml/scoring.py
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import sys
    import os
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

    print("=" * 60)
    print("AAROGYA Baseline Scoring Engine — Quick Test")
    print(f"Score Version: {SCORE_VERSION}")
    print("=" * 60)

    # Test Product A — relatively healthy product
    product_a = pd.Series({
        "product_name":               "Oat Muesli No Added Sugar",
        "sugar_g_100g":               14.5,
        "protein_g_100g":             9.8,
        "fiber_g_100g":               8.5,
        "sodium_mg_100g":             60.0,
        "saturated_fat_g_100g":       1.5,
        "energy_kcal_100g":           352.0,
        "processing_level":           "minimally_processed",
        "contains_whole_grain":       "true",
        "contains_artificial_sweetener": "false",
    })

    # Test Product B — ultra-processed, high sugar
    product_b = pd.Series({
        "product_name":               "Choco Cream Sandwich Biscuit",
        "sugar_g_100g":               32.0,
        "protein_g_100g":             5.5,
        "fiber_g_100g":               1.8,
        "sodium_mg_100g":             380.0,
        "saturated_fat_g_100g":       8.5,
        "energy_kcal_100g":           490.0,
        "processing_level":           "ultra_processed",
        "contains_whole_grain":       "false",
        "contains_artificial_sweetener": "false",
    })

    for label, product in [("Product A", product_a), ("Product B", product_b)]:
        result = compute_aarogya_score(product)
        print(f"\n{label}: {product['product_name']}")
        print(f"  Final Score   : {result['final_score']}/100 (v{result['score_version']})")
        print(f"  Components    : {result['component_scores']}")
        print(f"  Modifiers     : {result['modifiers']}")
        print(f"  Strengths     : {result['breakdown']['strengths']}")
        print(f"  Concerns      : {result['breakdown']['concerns']}")

    # Test with dataset
    demo_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "data", "raw", "aarogya_food_products_demo.csv"
    )
    if os.path.exists(demo_path):
        df = pd.read_csv(demo_path)
        df_scored = score_dataframe(df)
        print(f"\nDataset Scoring Summary:")
        print(f"  Products scored: {len(df_scored)}")
        print(f"  Score range:     {df_scored['computed_score'].min():.1f} – {df_scored['computed_score'].max():.1f}")
        print(f"  Mean score:      {df_scored['computed_score'].mean():.1f}")
        print(f"  Std deviation:   {df_scored['computed_score'].std():.1f}")
        print(f"\nTop 5 products by computed score:")
        top5 = df_scored[["product_name", "category", "computed_score"]].nlargest(5, "computed_score")
        print(top5.to_string(index=False))
        print(f"\nBottom 5 products by computed score:")
        bot5 = df_scored[["product_name", "category", "computed_score"]].nsmallest(5, "computed_score")
        print(bot5.to_string(index=False))
    else:
        print(f"\nNote: Demo dataset not found at {demo_path}")
        print("Run this script from the aarogya/ root directory.")

    print("\n[SCORING ENGINE OK]")
